import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { Nunito } from "next/font/google";

import BackgroundLayers from "./_components/BackgroundLayers";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"], // choose weights you need
  variable: "--font-nunito", // optional: for Tailwind config
});
export const metadata: Metadata = {
  title: "Dimtech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunito.variable}>
      <body className="font-nunito">
        <Providers>
          {children}
          {/* <BackgroundLayers></BackgroundLayers> */}
        </Providers>
      </body>
    </html>
  );
}
